# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Set to true to list unused volumes, false to delete them'
        required: true
        type: choice
        options: 
        - 'true'
        - 'false'
        default: 'true'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run list-unused-volumes.sh if dry-run is true
        if: ${{ github.event.inputs['dry-run'] == 'true' }}
        run: |
          chmod +x a.sh
          ./a.sh

      - name: Run delete-unused-volumes.sh if dry-run is false
        if: ${{ github.event.inputs['dry-run'] == 'false' }}
        run: |
          chmod +x b.sh
          ./b.sh
